### PR TITLE
Add BT VID, PID & add manufacturer ID to adv360_right_defconfig

### PR DESCRIPTION
**Pull request by zchee**
Currently, the `product_id` and `vendor_id` are still incorrect when ble transport (means zmk default values) even if used https://github.com/ReFil/zmk/tree/adv360-z3-beta to remote URL.

Override `CONFIG_BT_DIS_PNP_VID` and `CONFIG_BT_DIS_PNP_PID` to same as `CONFIG_USB_DEVICE_VID` and `CONFIG_USB_DEVICE_PID`.

### CODE REVIEW

**Comment by zchee** [comment]
cc: @ReFil

**Comment by ReFil** [comment]
The BT transport vid and PID are not the same as the usb vid and PID. Also the right side doesn't connect to the host and thus doesn't need those settings changing

**Comment by zchee** [comment]
> The BT transport vid and PID are not the same as the usb vid and PID. 

What pid is correct? just zmk default value?

> Also the right side doesn't connect to the host and thus doesn't need those settings changing

I see, thanks for advice. will remove.

**Comment by zchee** [comment]
Seems not require change. Close.

**Pull request closed without merging**
