### PR TITLE
refactor(boards): cleanup pins and keys, disable battery reporting

### PR DESCRIPTION
**Pull request by ReFil**
This cleans up the I/O mapping of the board, brings the keymap in line with the latest version of the manual and also functionally disables battery reporting, solving an issue on macs where it will repeatedly wake the computer from sleep. This is a stopgap until a new major firmware update where the bluetooth service for battery reporting will be removed

### CODE REVIEW

**Comment by fuchodeveloper** [comment]
👍🏼 glad to see the “frequent wake from sleep” bug being worked on.

**Comment by trein** [comment]
The refactoring commit creates major conflicts for anyone who has a custom keymap, which I imagine is everyone. I'm essentially rebasing from upstream and reverting the entire refactoring. That makes me wonder:

- How do you envision the workflow that users need to follow to update their forks? Are you expecting them to understand the changes and cherry-pick only the commits they want? I'm not sure if the average user will have the technical knowledge and/or the patience to go over all the changes trying to figure out what commit they need to cherry-pick  and the changes it depends on.

- Is there a better way to organize the files so that the keymap configuration is never touched? Or maybe changes should be backwards compatible and properly versioned? It sounds to me that this refactoring should have been part of a different major version and the bluetooth change something that should have been back-ported to earlier versions.

**Comment by ReFil** [comment]
Apologies for a lack of clarity surrounding this update, unfortunately there was no option but to push a breaking change as this resolved several outstanding issues permanently. all that needs to be done to bring an old keymap file up to new is removing the highlighted extraneous &none keys in the .keymap file and editing the keymap.json file to match. everything else should work without any changes. 

244104004-b9d696e0-6c6b-4f2c-a95e-85458b6ffb0e

**Comment by trein** [comment]
Thank you so much for the explanation above, @ReFil. Really appreciated.

I think I'm failing to understand how the refactoring and the bluetooth change are related. From my limited understanding of the code, they seem pretty independent. Couldn't the bluetooth fix be pushed to V2.0 and the breaking changes to V3.0 (or some other versioning scheme that this repo is following)?

**Pull request merged**
