### PR TITLE
update to latest firmware non-interactively

### PR DESCRIPTION
**Pull request by ghost**
The documentation suggests pressing the reset button then moving the file over to the partition via the mouse.  I prefer a non-interactive (other than pressing Mod + Hotkey 1 and 3) which also checks for the gotcha of using different versions.  It's linux specific and I only tested this on Debian but might get the ball rolling.

### CODE REVIEW

**Comment by ReFil** [comment]
Hiya, this looks interesting, I'll spin up my linux laptop and give it a go, would this work on macOS?

**Comment by ghost** [comment]
I have never used macOS so I would say "no".  It works for me
on Debian 11 and while I have not tested it probably will on 
Ubuntu, too.  Open to feedback.  Perhaps an OS specific function 
to detect that the device and mount the device?  I will not be 
able to test other than Linux.

It's not good practice to add the '.sh' extension to shell scripts 
but I did it for consistency with run.sh and setup.sh.  As they
are now gone, I will drop the extension.

**Comment by ghost** [comment]
This works fine.  It would make sense add support for settings-reset.  The documented procedure is to reset both boards, then install the new left and right firmware.  This triggers two problems: you can't can't do mod + hotkey 3 after the settings reset of the left board, and with both boards having their settings reset they will both be mountable.  The answer for the first problem is probably to do a reset then firmware load on the left side, then do the right side but I need someone from Kinesis to confirm that would work (it seem to for me for the same version but may not across versions).  If we can do one side at a time then it eliminates 2nd problem, however, it would be better if the script could verify that it's indeed operating on the left or right side.  It appears the magic is the  `iProduct` field of `lsusb -v` which is `Adv360 Pro` for the left side, and `Adv360 Pro rt` for the right side.  You can go from a usb entry to a disk device path via  the `iSerial` field which gets encoded in `/dev/disk/by-id/usb-Adafrut_*$serial*`.  It would be preferable if I could do it by-path, ideally, from digging something suitable out of /sys instead of `lsusb` which may not be installed.

**Comment by ReFil** [comment]
The latest version of settings_reset in this repository should automatically kick the board back into bootloader

**Comment by ghost** [comment]
Yes, it does ("both boards having their settings reset they will both be mountable.").  Sorry, I am afraid that I am missing what you are trying to tell me.

**Comment by ReFil** [comment]
Oh sorry I misunderstood what you were trying to say. The boards can usually retain their pairings across update but not advisable for big updates

**Comment by ghost** [comment]
Why is it not advisable?  I assume you just don't test (for good reason) all older versions against the current version to have any idea if it will work.  I think it's worth doing just for convenience of not having to find a tool to double click the reset button.

**Comment by ReFil** [comment]
Zephyr has a built in settings mechanism where the paired addresses are stored, and the microcontroller stores the keys in its own hardware too. The data is maintained through most updates however occasionally zmk updates the base zephyr version it's built on top of and this can cause unexpected behaviour if the settings subsystem changed between updates. As a general rule if you're changing the keymap or updating within the zephyr version you don't need to reset the settings, it's only moving across zephyr versions where it can be a good idea, and that only happens once every 6+ mo

**Comment by ghost** [comment]
Just a heads-up that I am returning my Advantage 360 Pro so I will lose the ability to test this shortly.  This PR works on Linux (without reset support) as is.

**Pull request closed without merging**
