### PR TITLE
Update README.md to account for new makefile setup

### LINKED ISSUE #56: Instructions in README fail
# `make all`

Fails with:

```
docker run --rm -it --name zmk \
	-v /home/jason/projects/keyboard/adv360/Adv360-Pro-ZMK/firmware:/app/firmware \
	-v /home/jason/projects/keyboard/adv360/Adv360-Pro-ZMK/config:/app/config:ro \
	-e TIMESTAMP=20221115171029 \
	zmk
usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: 'build' (choose from 'init', 'update', 'list', 'manifest', 'diff', 'status', 'forall', 'help', 'config', 'topdir', 'selfupdate')
make: *** [Makefile:9: all] Error 2
```

# `make build`

`make build` fails as there is no `build` target in the `Makefile`.

### PR DESCRIPTION
**Pull request by ReFil**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
`make` and `make all` is the same thing with this config file I suggest you just use the former.  The `make install` feature was merged so we should mention that in step 2 as an option on Linux (and welcome suitable changes on other platforms) and maybe note official process which was to put both boards into update mode (or whatever it was called).  The write-up you did for me when it was required was really good.

For completeness, let's mention `make clean` to remove accumulated firmware and removal of the containers. 

Sorry, I should have updated the readme.txt.  The file was being actively modifying when I made those changes initially.

Happy to do another review.

**Review by jasonish — APPROVED** [review]
Looks good to me.

**Comment by ReFil** [comment]
@allanwind The make install stuff wasn't merged afaik, but i've made the other changes you suggested including mentioning the clean up stuff. I also added firmware install instructions linking to the kinesis QSG

**Review by ghost — APPROVED** [review]
Looks great and you can ship it as is.

The document would look simpler if you just have two sections (Github, localhost) and list the steps sequentially.   You can mark the setup steps with "(once)" but I think it would be clear implied.

"Note: Either Podman or Docker is required, Podman is preferred if both are present. If compiling on Windows use WSL2 and docker [Docker Setup Guide](https://docs.docker.com/desktop
/windows/wsl/)." is a little verbose.  What about calling "Install container run-time" then as bullets for the alternatives:  + On Windows use WSL2 and docker [Docker Setup Guide](https://docs.docker.com/desktop/windows/wsl/)."  Otherwise Docker or Podman (latter is preferred if both are installed).  Is "latest" clear?  It was for me.

I.e. along these lines:

# Github

1. (once) Fork this repo.
2. (once) Enable GitHub Actions on your fork (how?)
3. Push a commit to trigger the build.
4. Download the artifact (where?)
5. [Quick Start Guide](https://kinesis-ergo.com/wp-content/uploads/Advantage360-Professional-QSG-v8-25-22.pdf), p. 8 tells you how to install the two new firmware files.

# Local

1. (once) Install container run-time
    + On non-Windows use Docker or Podman (latter is preferred if both are available).
    + On Windows use WSL2 and docker [Docker Setup Guide](https://docs.docker.com/desktop/windows/wsl/).
2. `make`
3. [Quick Start Guide](https://kinesis-ergo.com/wp-content/uploads/Advantage360-Professional-QSG-v8-25-22.pdf), p. 8 tells you how to install the two latest firmware files (`ls firmware | tail -2`).

Maybe even one list (I have to write it out to tell if it's better or worse):

1. Setup your environment and build firmware.  You can do so either on github or on your localhost:
    + github
        1. (once) Fork this repo.
        2. (once) Enable GitHub Actions on your fork (how?)
        3. Push a commit to trigger the build.
        4. Download the artifact (where?)
     + localhost
        1. (once) Install container run-time
            + On non-Windows use Docker or Podman (latter is preferred if both are available).
            + On Windows use WSL2 and docker [Docker Setup Guide](https://docs.docker.com/desktop/windows/wsl/).
       2. `make`
       3. The latest two firmware files (`ls firmware | tail -2`) is the ones you just build
2. [Quick Start Guide](https://kinesis-ergo.com/wp-content/uploads/Advantage360-Professional-QSG-v8-25-22.pdf), p. 8 tells you how to install the firmware files.

**Comment by ReFil** [comment]
That's a good idea, i'll do that, documentation isn't really my strong suit so i appreciate the advice :)

**Comment by ghost** [comment]
I find it hard, too :-)

**Review by ghost — APPROVED** [review]
All the sections make it look more complicated than it is.  Did you see the write up using a single enumerated list?  In either case feel free to ship it.

**Comment by ReFil** [comment]
Thanks for the advice. I wanted to give enough information to make it easier, although I can see how it can look quite complicated, it's a hard balance to walk. I think I'll leave it as is

**Pull request merged**
