### PR TITLE
Document new layer colors and modifier color configuration option

### PR DESCRIPTION
**Pull request by khoek**
Add documentation for https://github.com/ReFil/zmk/pull/18 and https://github.com/ReFil/zmk/pull/19.

Here it is [rendered](https://github.com/khoek/Adv360-Pro-ZMK/blob/new-docs/README.md#modifier-indicator-color).

### CODE REVIEW

**Comment by ReFil** [comment]
`CONFIG_ZMK_RGB_UNDERGLOW_MOD_COLOR` needs to be set on both sides right? it may be worth clarifying that in the docs

**Comment by khoek** [comment]
Sorry, I'd missed this.

**Comment by ReFil** [comment]
Please can you rebase as there were some other changes to the zephyr 3.5 PR? It would also be good if you could link to the base ZMK PR's in the changelog entries. Thank you

**Comment by khoek** [comment]
How does that look?

**Comment by ReFil** [comment]
Spot on, thank you very much!

**Comment by ReFil** [comment]
Waiting for build job then i'll hit merge, thank you again for all your work on these features <3

**Pull request merged**
