### PR TITLE
Fix MacOS makefile vvars

### PR DESCRIPTION
**Pull request by ReFil**
### What's changed:

The OS auto detection in the makefile has been expanded so more variables are not quoted when running under MacOS

### Why has this change been implemented:

#335 Broke compatibility on MacOS

### What (if any) actions must a user take after this change:

No additional actions need to be taken

### CODE REVIEW

**Review by gaheeoh — COMMENTED** [review]
pulls from  kinesis

**Comment by huber-th** [comment]
Is this an issue for a specific version of macOS? I'm on Sonoma 14.3 (Apple Silicon M2) and have no issues with the OS detection as it is implemented in branch `V3.0`

**Comment by ReFil** [comment]
Not sure, We had a user reporting this as an issue but i cant for the life of my find the issue report now

**Comment by ReFil** [comment]
Closing as seems to be unnecessary

**Pull request closed without merging**
