### PR TITLE
Add debounce configuration values

### PR DESCRIPTION
**Pull request by lyallcooper**
I've been experiencing key chatter/bounce issues with my Advantage360, and upon inspection it seems that the press and release debounce config values are both set to `-1` according to the build logs. Unless I'm missing configuration somewhere else, this means the firmware is effectively doing no debouncing.

Here I've set the values to the [ZMK defaults](https://zmk.dev/docs/features/debouncing), which are 5ms for both. On my own board this has removed the key bounce issue without adding any perceptible delay.

It's possible that this is just an issue with my board, but if debounce really is disabled then I'd expect _most_ people to experience this same issue to a certain degree.

### CODE REVIEW

**Comment by ReFil** [comment]
The debouncing values should be set to default, not sure why they wouldn't be, either way creating a new file called adv360.conf is not ideal, please put these values into adv360_left_defconfig and adv360_right_defconfig instead

**Comment by lyallcooper** [comment]
Thanks for taking a look.

After digging into it some more, you're right that the [debounce values should've been set to default already](https://zmk.dev/docs/config/kscan#kconfig). I've been playing around with this some more and even after removing these config value I added, my key bounce issue still seems to be fixed. My only theory now is that there was some other strange internal state or bluetooth connection issue that was causing the problem, and that flashing the `settings-reset.u2f` file, which I happened to do right before trying the firmware with these config values set, did something to fix the issue.

Also it seems very unlikely that the debounce could really be set to 0—otherwise I'd expect everyone with an Advantage360 Pro to be complaining about key bounce.

I'll close this PR now. Just hoping that the key bounce issue doesn't mysteriously start happening again 🤞

**Comment by mstarodub** [comment]
> The debouncing values should be set to default, not sure why they wouldn't be, either way creating a new file called adv360.conf is not ideal, please put these values into adv360_left_defconfig and adv360_right_defconfig instead

Question about this since this is one of the few references I found about that file on the issue tracker:

Zmk documentation mentions this file:

https://zmk.dev/docs/keymaps/behaviors/bluetooth#bluetooth-pairing-and-profiles

Should all configuration go into both the left and the right defconfig instead, always? Thank you.

**Comment by ReFil** [comment]
Yes, the .conf approach is for a different kind of config repo compared to what the 360 pro uses

**Pull request closed without merging**
