### PR TITLE
Update bluetooth settings in light of user feedback

### PR DESCRIPTION
**Pull request by ReFil**

### CODE REVIEW

**Comment by ReFil** [comment]
Should address #282

**Comment by gshpychka** [comment]
Can you list what the changes actually do and affect? Will commenting out `CONFIG_BTC_PRIVACY=n` result in us being unable to enter the password on MacOS login screen?

**Comment by ReFil** [comment]
@gshpychka The bluetooth LE connection parameters have been changed to improve compatibility with macOS. setting CONFIG_BT_PRIVACY=n is functionally the same as commenting it out so nothing has changed in that regard

**Comment by gshpychka** [comment]
> @gshpychka The bluetooth LE connection parameters have been changed to improve compatibility with macOS. setting CONFIG_BT_PRIVACY=n is functionally the same as commenting it out so nothing has changed in that regard

Understood, thanks. Still, can you clarify what those settings did and what exactly changed?

**Comment by ReFil** [comment]
The settings controlled some low level parameters of the Bluetooth connection. They were set according to the apple accessory device specification at the time. A few months ago Apple revised the accessory specification and we changed our settings accordingly

**Pull request merged**
