### PR TITLE
Add additional pedal keys

### PR DESCRIPTION
**Pull request by ReFil**
Adds pedal2 keys on left and right back into matrix, can help sort mystery keypresses

### CODE REVIEW

**Comment by ottobonn** [comment]
Hello, it looks like this might have broken the generated keymaps of the GUI editor. Now the maps it generates have the keys shifted over because it is not producing placeholders for the pedals.

**Comment by ReFil** [comment]
Sorry about this, just waiting for the fix to test build then i will merge the fix

**Comment by tarsius** [comment]
> can help sort mystery keypresses

I have assumed that the pedal keys were there for purely cosmetic reasons; to help generating images of the keyboard, or something like that. I found them distracting and was considering removing them eventually. Would you be so kind and briefly explain how these fake keys help with avoiding mystery keypresses? Thanks!

**Comment by OlivierNicole** [comment]
> can help sort mystery keypresses

This seems to solve the issue of out-of-thin-air keypresses that I’ve been having. I have no idea why, but well… good news for me.

**Pull request merged**
